#!/usr/bin/env bash

set -e

case "$1" in
   "publish")
       version=""
       local=false

       while [[ $# -gt 1 ]]; do
           case "$2" in
               --version)
                   version="$3"
                   shift 2
                   ;;
               --local)
                   local=true
                   shift
                   ;;
               *)
                   echo "Unknown publish argument: $2"
                   exit 1
                   ;;
           esac
       done

       export PUBLISHING=true
       if [[ "$local" = true ]]; then
           if [[ -z "$version" ]]; then
               echo "Version required for local publish"
               exit 1
           fi

           echo "Publishing version $version locally..."
           ./gradlew publishToMavenLocal -x dokkaGeneratePublicationHtml -PVERSION_NAME="${version}" --rerun-tasks
       else
           echo "Publishing version $version..."
           ./gradlew publish -x dokkaGeneratePublicationHtml
       fi
       ;;

   "check")
       echo "Running checks..."
       ./gradlew check -x dokkaGeneratePublicationHtml
       ./gradlew -p samples check
       ;;

   "clean")
       echo "Cleaning..."
       ./gradlew clean
       ./gradlew -p samples clean
       ;;

   "format")
       echo "Applying formatting..."
       ./gradlew spotlessApply --no-configuration-cache
       ./gradlew -p samples spotlessApply --no-configuration-cache
       ;;

   "regen")
       echo "Applying formatting and API gen..."
       # Annoyingly, the apiDump task has some caching issues
       ./gradlew spotlessApply apiDump --rerun-tasks --no-build-cache --no-configuration-cache
       ./gradlew -p samples spotlessApply --no-configuration-cache
       # https://youtrack.jetbrains.com/issue/KT-69684
       ./gradlew clean
       rm -rf kotlin-js-store
       rm -rf samples/kotlin-js-store
       ./gradlew kotlinWasmUpgradePackageLock kotlinUpgradePackageLock --rerun-tasks --no-build-cache
       ./gradlew -p samples kotlinWasmUpgradePackageLock kotlinUpgradePackageLock --rerun-tasks --no-build-cache
       ;;

   *)
       echo "Usage: metrow (publish|check|clean|format|regen)"
       echo "publish options:"
       echo "  --version <version>  Specify version for publishing"
       echo "  --local              Publish locally"
       exit 1
       ;;
esac
