package dev.zacsweers.metro.compiler;

import com.intellij.testFramework.TestDataPath;
import java.io.File;
import java.util.regex.Pattern;
import org.jetbrains.kotlin.test.TestMetadata;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.junit.jupiter.api.Test;

/**
 * This class is generated by {@link dev.zacsweers.metro.GenerateTestsKt}. DO NOT MODIFY MANUALLY
 */
@SuppressWarnings("all")
@TestMetadata("compiler-tests/src/test/data/diagnostic")
@TestDataPath("$PROJECT_ROOT")
public class DiagnosticTestGenerated extends AbstractDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostic() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(
        this.getClass(),
        new File("compiler-tests/src/test/data/diagnostic"),
        Pattern.compile("^(.+)\\.kt$"),
        null,
        true);
  }

  @Test
  @TestMetadata("ProvidesMustBePrivateWarn.kt")
  public void testProvidesMustBePrivateWarn() {
    runTest("compiler-tests/src/test/data/diagnostic/ProvidesMustBePrivateWarn.kt");
  }

  @Test
  @TestMetadata("ProvidesMustHaveBody.kt")
  public void testProvidesMustHaveBody() {
    runTest("compiler-tests/src/test/data/diagnostic/ProvidesMustHaveBody.kt");
  }
}
